### PR TITLE
feat(hsection): add HSection & collapsable ability

### PR DESCRIPTION
**Pull request by Thienhuynh95**
## Description

This PR adds `HSection` with collapsable ability and rename `Section` component to `VSection`

## Todo

- [ ] Bump version and add tag

### CODE REVIEW

**Review by evad1n — APPROVED** [review]
I think it might be nice to see an HSection/Vsection story with multiple parts as children. That would reflect most of our use cases, especially for the collapsible one. What do you think?

**Comment by Thienhuynh95** [comment]
> I think it might be nice to see an HSection/Vsection story with multiple parts as children. That would reflect most of our use cases, especially for the collapsible one. What do you think?

Thanks for the feedback. Which multiple parts you would like to see? Do you mean all states (collapse, expand, long subtitle) in one story?

**Review by evad1n — APPROVED** [review]

**Comment by evad1n** [comment]
Just a p

> > I think it might be nice to see an HSection/Vsection story with multiple parts as children. That would reflect most of our use cases, especially for the collapsible one. What do you think?
> 
> Thanks for the feedback. Which multiple parts you would like to see? Do you mean all states (collapse, expand, long subtitle) in one story?

Just something to show how it looks in common cases, so surrounded by other sections as well where you can collapse each section.

**Comment by Thienhuynh95** [comment]
Sounds good, I'll put that in the next PR. Thanks 😄

**Pull request merged**
