### PR TITLE
update/All icons

### PR DESCRIPTION
**Pull request by ckgardner**
## Description

This PR updates all of the icons that have changed in Figma. Solid icons have been removed and white icons have been added. The reason white icons were needed is because they have a larger thickness than the black icons in order to stand out on a black background. 

## Todo

- [x] Bump version and add tag

### CODE REVIEW

**Comment by evad1n** [comment]
So from the following image it looks like the white icon is the one with less thickness, which means it is supposed to be used on a white background, while the normal one is slightly thicker, which should be used for dark backgrounds?
image

**Review by evad1n — DISMISSED** [review]
Went through and looked at some of the components and it looks good 👍

**Comment by Thienhuynh95** [comment]
@evad1n According to the Figma, `White` icons are being located in the black background, so I assume `White` will be used on DarkMode, and the other rest is regular mode 👀

**Comment by evad1n** [comment]
Huh, that makes sense I think. Some confusing naming though.

**Comment by Thienhuynh95** [comment]
😆 You don't say 🙄

**Review by Thienhuynh95 — DISMISSED** [review]
Looks great!

**Review by goodpickle — APPROVED** [review]

**Pull request merged**
