### PR TITLE
fix: overflow auto when fully expanded

### PR DESCRIPTION
**Pull request by evad1n**
## Description

Fixes an issue with the `Collapse` component where `overflow: hidden` was causing box shadows (and anything outside the components bounding box) to be hidden.

Also made the Collapse story slightly nicer.

## Todo

- [ ] Bump version and add tag

### CODE REVIEW

**Review by goodpickle — APPROVED** [review]

**Review by jaxonjporter — APPROVED** [review]
I like your solution.

**Comment by evad1n** [comment]
Ha, it was the least code solution

**Comment by jaxonjporter** [comment]
> Ha, it was the least code solution

I dont know, padding: 2px probably would have been the least code lol

**Comment by evad1n** [comment]
> > Ha, it was the least code solution
> 
> I dont know, padding: 2px probably would have been the least code lol

I wouldn't consider that a good solution 😆

**Pull request merged**
